//This file is automatically generated by scripts/parseDataFolders.js

type IDataAssetMap<Type extends string> = {
  [key in Type]: string;
};

export const UNITS = ['basic_axe', 'basic_bow', 'dwarf', 'guard', 'knight_green', 'lizard', 'monk', 'mooseman', 'oldman', 'rhino', 'troll'] as const;
export type UNIT_TYPE = typeof UNITS[number];
const UNIT_ASSETS : IDataAssetMap<UNIT_TYPE> = {
  basic_axe : 'assets/data/units/basic_axe.json',
  basic_bow : 'assets/data/units/basic_bow.json',
  dwarf : 'assets/data/units/dwarf.json',
  guard : 'assets/data/units/guard.json',
  knight_green : 'assets/data/units/knight_green.json',
  lizard : 'assets/data/units/lizard.json',
  monk : 'assets/data/units/monk.json',
  mooseman : 'assets/data/units/mooseman.json',
  oldman : 'assets/data/units/oldman.json',
  rhino : 'assets/data/units/rhino.json',
  troll : 'assets/data/units/troll.json'
};

export const AURAS = ['cannibalize', 'damage_boost', 'holy_strength'] as const;
export type AURA_TYPE = typeof AURAS[number];
const AURA_ASSETS : IDataAssetMap<AURA_TYPE> = {
  cannibalize : 'assets/data/auras/cannibalize.json',
  damage_boost : 'assets/data/auras/damage_boost.json',
  holy_strength : 'assets/data/auras/holy_strength.json'
};


export const DATA_ASSET_MAP = {
  units : UNIT_ASSETS,
  auras : AURA_ASSETS,
};
