const { statSync, readdirSync, writeFileSync } = require('fs');
const { join, extname } = require('path');
const _ = require('lodash');

const DATA_PATH = "./src/assets/data/"
const UNITS_PATH = "units/"
const AURAS_PATH = "auras/"

const PATH_OUTPUT_ASSET_LIST = './src/scripts/game/assets/AssetList.ts';

const json_files = p => readdirSync(p).filter(f=>statSync(join(p,f)).isFile() && extname(f) === ".json");


let FILE_CONTENT = ``;

FILE_CONTENT += 
`//This file is automatically generated by scripts/parseDataFolders.js
`

FILE_CONTENT += 
`
type IDataAssetMap<Type extends string> = {
  [key in Type]: string;
};
`


FILE_CONTENT += 
`
export const UNITS = [`

const unit_jsons = json_files(DATA_PATH + UNITS_PATH);
_.forEach(unit_jsons, (name, index) => {
  const id = name.split('.json')[0];
  const last = index === unit_jsons.length - 1;

  FILE_CONTENT += `'${id}'${last ? ']' : ', '}`;
});

FILE_CONTENT += ` as const;`;
FILE_CONTENT += `
export type UNIT_TYPE = typeof UNITS[number];
`


FILE_CONTENT += 
`const UNIT_ASSETS : IDataAssetMap<UNIT_TYPE> = {
`

_.forEach(unit_jsons, (name, index) => {
  const id = name.split('.json')[0];
  const last = index === unit_jsons.length - 1;
  FILE_CONTENT += 
`  ${id} : '${'assets/data/' + UNITS_PATH + name}'${last ? '' : ','}
`
});

FILE_CONTENT += 
`};
`


FILE_CONTENT += 
`
export const AURAS = [`

const aura_jsons = json_files(DATA_PATH + AURAS_PATH);
_.forEach(aura_jsons, (name, index) => {
  const id = name.split('.json')[0];
  const last = index === aura_jsons.length - 1;

  FILE_CONTENT += `'${id}'${last ? ']' : ', '}`;
});
FILE_CONTENT += ` as const;`;
FILE_CONTENT += `
export type AURA_TYPE = typeof AURAS[number];
`


FILE_CONTENT += 
`const AURA_ASSETS : IDataAssetMap<AURA_TYPE> = {
`

_.forEach(aura_jsons, (name, index) => {
  const id = name.split('.json')[0];
  const last = index === aura_jsons.length - 1;
  FILE_CONTENT += 
`  ${id} : '${'assets/data/' + AURAS_PATH + name}'${last ? '' : ','}
`
});

FILE_CONTENT += 
`};
`


FILE_CONTENT += `

export const DATA_ASSET_MAP = {
  units : UNIT_ASSETS,
  auras : AURA_ASSETS,
};
`;

// console.log(FILE_CONTENT);
console.log("Writing file: " + PATH_OUTPUT_ASSET_LIST);
writeFileSync(PATH_OUTPUT_ASSET_LIST, FILE_CONTENT);
console.log('finished');
